Repository mathematicalmichael/cafelytics, pull requests merged in 2020-08, with the labels that each got.

#15 Develop
  README.md
  data/demoData.csv
  data/growth.yml
  data/trees.yml
  fakeData.py
  farm.py
  importData.py
  intervention/strategy1.yml
  simulateCoOp.py
Labels: good first issue

#22 Stage changes for packaging, remove matlab files
  index.ipynb
  src/ImportSurvey.m
  src/ProdSimulation.m
  src/Worksheet.m
  src/cafelytics/__init__.py
  src/comparativeline.m
Labels: enhancement, good first issue

#20 packaging, unit testing and coverage
  .coveragerc
  .github/workflows/test-coverage.yml
  .gitignore
  README.md
  setup.cfg
  setup.py
  src/cafe/__init__.py
  src/cafe/fakeData.py
  src/cafe/farm.py
  src/cafe/importData.py
  src/cafe/simulateCoOp.py
  tests/conftest.py
  tests/test_fakeData.py
  tests/test_farm.py
Labels: enhancement
